  bond_reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config
        uses: actions/checkout@v3
      - name: Install west and deps
        run: |
          pip install west
      - name: Init and Update west
        run: |
          west init -l .
          west update
      - name: Build Bond Reset (nice_nano_v2, my_macro_pad)
        run: |
          west build -b nice_nano_v2 -- -DSHIELD=my_macro_pad -DCONFIG_ZMK_BOND_CLEAR=y
      - name: Upload bond reset UF2
        uses: actions/upload-artifact@v4
        with:
          name: bond-reset
          path: build/zephyr/zmk.uf2
