name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3

  bond_reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config
        uses: actions/checkout@v3
      - name: Build Bond Reset (nice_nano_v2, my_macro_pad)
        uses: zmkfirmware/zmk/.github/actions/build@v0.3
        with:
          board: nice_nano_v2
          shield: my_macro_pad
          extra-cmake: -DCONFIG_ZMK_BOND_CLEAR=y
      - name: Upload bond reset UF2
        uses: actions/upload-artifact@v4
        with:
          name: bond-reset
          path: build/zephyr/zmk.uf2
